### ISSUE TITLE
Error for some streams and menu entries

### ISSUE THREAD

**Issue by macardi** [Ikosse/plugin.video.teliaplay-se#1]
First of all, thanks for a great addon!
 
I have two issues. First some (not all) of the live channels doesn’t work, when I try to start a stream from the channels entry (TV or På TV) Kodi throws me an error and the playback fails.
 
I also experience problems with some of the menu entries where the following error appears when I choose a menu entry “PERSISTED_QUERY_NOT_FOUND”. 
 
I the log I first try to start a stream from the channels entry (TV), witch fails. After that I try to enter a  menu entry where I got the error mentioned above. 
 
Let me know if you need more information. Hope you can find a fix for these problems
 
[Log](https://paste.kodi.tv/ewupusayip.kodi)

Cheers
Marcus

**Comment by macardi** [comment]
Excellent, thank you!

**Comment by Ikosse** [comment]
Not sure what the problem could be for those channels. My guess is that there could be some extra variables sent with the request; however, since I don't have a paid subscription I have no way of inspecting it.

**Comment by macardi** [comment]
Ok, thanks for looking in to it. Is there any information i can provide that could be usefull?

**Comment by Ikosse** [comment]
Ok, I think I have found the issue; there was a query variable that limited the number of channels retrieved to only 20. As a temporary fix I increased the number of channels to 100. If you need more channels than that, just set the variable CHANNEL_LIMIT (line number 5) in https://github.com/Ikosse/plugin.video.teliaplay-se/blob/master/resources/lib/api.py to however many you need. I will fix it by pagination as soon as I get some time. Please let me know if it is working. :)

**Comment by Ikosse** [comment]
Regarding why some stream fails, what I can infer from your log file it seems to stem from an IndexError. I tried fixing it very naively by catching the exception and trying again. Not sure if it will work; could you please try starting a stream that previously failed? If it still fails I need to see the new log file.

**Comment by macardi** [comment]
Big thanks again for trying to solve this!

However now I cant start the addon, got an error directly and the addon does not start.

[Log](https://paste.kodi.tv/rakafadaye.kodi)

**Comment by Ikosse** [comment]
Of course I have mixed tabs and spaces. Now that shouldn't be a problem at least.

**Comment by macardi** [comment]
Yes, now its working! Good job, really appreciate it, thanks so much!

**Comment by Ikosse** [comment]
Excellent! I will close this issue then. If you run into more problems, don't hesitate to open a new issue; your feedback is highly valuable to me!
