### ISSUE TITLE
Ubuntu 

### ISSUE THREAD

**Issue by klusbert** [Ikosse/plugin.video.teliaplay-se#3]
I cant ger this to work on kodi on ubuntu.
And I do not find any information in the logs

**Comment by klusbert** [comment]
Found the log now:
s
2022-01-13 19:20:26.886 T:98663   ERROR <general>: CCurlFile::FillBuffer - Failed: SSL connect error(35)
2022-01-13 19:20:26.886 T:98663   ERROR <general>: CCurlFile::Open failed with code 0 for https://wvls.webtv.telia.com:8063/:
                                                   
2022-01-13 19:20:26.887 T:98663   ERROR <general>: AddOnLog: inputstream.adaptive: License server returned failure
2022-01-13 19:20:26.887 T:98663   ERROR <general>: AddOnLog: inputstream.adaptive: License update not successful (no keys)
2022-01-13 19:20:26.917 T:98663   ERROR <general>: AddOnLog: inputstream.adaptive: Initialize failed (SingleSampleDecrypter)
2022-01-13 19:20:26.923 T:98663   ERROR <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.teliaplay-se/?menu=play&streamType=live&streamId=4]

**Comment by Ikosse** [comment]
Hello,

Thank you for reporting. Can you please post the whole log using https://paste.kodi.tv/ with debugging enabled both in kodi and in the Telia Play SE settings?
Also, which version of the add-on are you using?

**Comment by klusbert** [comment]
https://paste.kodi.tv/oqutayebin.kodi

**Comment by Ikosse** [comment]
Hmm, I am not able to reproduce this error, at least not on Arch, but I doubt it is distribution related. Just thinking out loud here; if I recall correctly there were two widevine keys to choose from, depending on whether the stream is vod or live type. The failure in this case occurs when you try to stream the TV4 live channel, right? It could be that, for some reason, the vod key is chosen instead of the live key. The logic for choosing which key to use is largely ad-hoc and can certainly be improved. I will look into it, and push an update as soon as I get some spare time.

**Comment by klusbert** [comment]
I should have mentioned that I have tried this on my main machine also ubuntu with same result. However it works great on both windows 10 and android. I will try manjaro when I have time to see if it works.

**Comment by Ikosse** [comment]
So I looked into the issue and can indeed confirm that the add-on does not seem to work properly on Ubuntu 20.04 LTS with Kodi 19.3. The culprit seems to be in the system Python installation, as the add-on worked as expected when I switched to using a custom miniconda Python installation.

**Comment by klusbert** [comment]
I tried to create with this conda create --name kodi2 python=3.8.10 and start kodi with this:

env PATH="/home/htpc /miniconda3/envs/kodi2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" LD_LIBRARY_PATH="/home/htpc/miniconda3 /envs/kodi2/lib" kodi

Still problem with the plugin how did you so it? Thanks again

**Comment by klusbert** [comment]
Got it to work create a conda env as I did above then:

env PATH="/home/htpc/miniconda3/envs/kodi2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" LD_LIBRARY_PATH="/home/htpc/miniconda3/envs/kodi2/lib" kodi

**Comment by Ikosse** [comment]
Great! I suppose only setting LD_LIBRARY_PATH and PATH is sufficient as long as the python version is the same as the one kodi was compiled against. In case the python versions differ I also had set LD_PRELOAD to link up against functions from the correct library, which in your case amounts to:

export LD_PRELOAD="/home/htpc/miniconda3/envs/kodi2/lib/libpython3.8.so
 
Of course one may also compile kodi directly against the desired python installation. Which I guess in the case of different python versions is the safer alternative.
