### ISSUE TITLE
Change stream bitrate?

### ISSUE THREAD

**Issue by ClasseM** [Ikosse/plugin.video.teliaplay-se#4]
Hello
Just wondering if there's any way to lower/change stream bitrate (or change to a stream with lower bitrate)?
If possible please advise how this can be lowered (i.e. where this is controlled in the code)?

Thanks for a great plugin!!

**Comment by Ikosse** [comment]
Hello,
The add-on itself does not control the bitrate of the stream, this is done by the external inputstream-adaptive add-on. You can configure it to manually select stream by going into the settings menu of the input-stream adaptive add-on. See here for more info: https://github.com/xbmc/inputstream.adaptive/wiki/Settings
