### ISSUE TITLE
Error when opening Telia app

### ISSUE THREAD

**Issue by macardi** [Ikosse/plugin.video.teliaplay-se#5]
Hi, since a couple of days I cant launch the plugin anymore. Kodi just returns an error and the plugin does not open.

[Log](https://paste.kodi.tv/danuvatuti.kodi)

Could you please look in to it.

Cheers
Marcus

**Comment by Ikosse** [comment]
I get the the impression that this is the version from the official repository; have you tried the one from this repository?

**Comment by macardi** [comment]
Yes i dowloded it from here. However I did it again and installed but the problem remains

**Comment by Ikosse** [comment]
Ok, looking closer at the error message there seems to be a problem when reading the data user file; perhaps some weird character has snuck in the username/password? Can you try deleting userdata.json file and then enter your credentials again? The file should be locatedl under $KODI/userdata/addon_data/plugin.video.teliaplay-se/userdata.json. It should also be removed if you choose to clear user data when removing the add-on.

**Comment by macardi** [comment]
Yes, it working again after removing that file. Thank you so very much.

**Comment by Ikosse** [comment]
Glad it worked out for you! I'll close this one as solved then.
